### PR TITLE
Minor spelling and datatype corrections and further consistency of parameter names

### PR DESCRIPTION
**Pull request by millen1m**

### CODE REVIEW

**Comment by zhuminjie** [comment]
May I know why do want to remove ExplicitDifference from integrator?

**Comment by millen1m** [comment]
Sorry I forgot to add that back in.

**Comment by zhuminjie** [comment]
No problem! I saw some randomly typed letters in one of the files. Maybe double check all the changes. Thank you!

**Comment by millen1m** [comment]
Great. I will merge the changes back into my latest branch and check them.

**Comment by zhuminjie** [comment]
> Great. I will merge the changes back into my latest branch and check them.

Thank you!

**Pull request merged**
