### PR TITLE
Modification of Concrete02

### PR DESCRIPTION
**Pull request by juandiegopozo**

### CODE REVIEW

**Comment by zhuminjie** [comment]
Is the change already in OpenSeesPy?

**Comment by juandiegopozo** [comment]
Oh sorry, I forgot to create the commits in OpenSeesPy. I have already done it.
Thanks.

**Comment by zhuminjie** [comment]
> Oh sorry, I forgot to create the commits in OpenSeesPy. I have already done it.
> Thanks.

I meant if the change already made in OpenSees repo. The OpenSeesPy repo uses git subtree to maintain a copy of OpenSees repo in its sub-folder. No need to send PR to OpenSeesPy. It will be updated if the main OpenSees is updated.

Actually, my question is that if the command change in Concrete02 is reflected in OpenSeesPy? Did you modify the OPS_Concrete02 or Tcl_Concrete02, not exact name but you know what I mean.

**Comment by juandiegopozo** [comment]
I see.. No, it is not reflected in OpenSeesPy yet. The pull request for updating Concrete02 in the OpenSees repo is still open.

**Comment by zhuminjie** [comment]
I see. I will merge this one once the PR is merged in OpenSees main repo.

**Comment by juandiegopozo** [comment]
Sounds good.
Thanks Minjie Zhu

**Comment by mhscott** [comment]
Not merged in main OpenSees because Concrete02IS is the same as what's desired.
https://github.com/OpenSees/OpenSees/pull/453

**Pull request closed without merging**
