### PR TITLE
TDConcrete models

### PR DESCRIPTION
**Pull request by ntosic87**
@zhuminjie I hope this is better, please let me know if not. Also, the models have yet to be added to the OpenSees master branch, a pull request is pending there also

### CODE REVIEW

**Comment by zhuminjie** [comment]
Thank you for sending it one more time. I see you delete the .gitignore file and change the ExplicitDifference.rst file. Are you intentional to do that?

**Comment by ntosic87** [comment]
No, but when I added my 4 new files in Visual Studio and edited uniaxialMaterial, automatically some files were added to vs. Thinking that you do not want any additions there I undid those changes there were then logged as gitignore which I then again deleted from my branch...
But the change in ExplicitDifference happens automatically I don't know why...
I just need to add the four TDConcrete files and place them in uniaxialMaterial, that is all.
Sorry for the hassle really

**Comment by ntosic87** [comment]
Also, in OpenSees itself, prof. Scott modified the code adding a global creep variable "setCreep", so I re-edited my code, synced with the master branch and resubmitted a pull request. So unless the materials are admitted there, there is probably no sense in adding them here.
I think they are very useful and interesting allowing the time-dependent analysis of concrete, but I'm no programmer so using GitHub and VisualStudio has been hit and miss...

**Comment by zhuminjie** [comment]
I understand you just want to add four TDConcrete files. But I can't do anything to modify your commits. What you can do is to undo all your commits and only add these four files, and commit them. You don't have to commit all changed files, just commit those you want to push up.

**Comment by ntosic87** [comment]
OK, let me try:)

**Pull request closed without merging**
