### PR TITLE
Adding Plotting Development Guide

### PR DESCRIPTION
**Pull request by u-anurag**
This guide describes what is happening in Get_Rendering code and explains the internal and user functions. It will be useful for new developers to streamline their code with the existing one.

### CODE REVIEW

**Comment by zhuminjie** [comment]
This is cool!

**Comment by zhuminjie** [comment]
Would it be possible to add more examples to show different functions of the plotting? You did a great job!

**Comment by u-anurag** [comment]
Thank you @zhuminjie! I'll add an example for each internal function and how to call them in a user function.

**Comment by zhuminjie** [comment]
Thank you @u-anurag !

**Pull request merged**
