### PR TITLE
Fix path import

### PR DESCRIPTION
**Pull request by sewkokot**
This PR:
1. uses simpler `import` instead of `exec/open/read` command as recommended in 
https://stackoverflow.com/questions/2349991/how-to-import-other-python-files
2. add info on setting PYTHONPATH env variable to avoid setting the path to OpenSeesPy directory for each example python file

### CODE REVIEW

**Comment by zhuminjie** [comment]
Thank you for the changes! But when change exec to import, the script doesn't run due to following error

File "RCFrameEarthquake.py", line 34, in <module>
    m = P/g
NameError: name 'P' is not defined

Can you fix it. Thank you!

**Comment by sewkokot** [comment]
We have 3 solutions then:
1. instead of "import RCFrameGravity" use "from RCFrameGravity import *"
2. with "import RCFrameGravity", use "m = RCFrameGravity.P/g" instead of "m=P/g", or 
3. stay with the previous "exec..."

**Comment by zhuminjie** [comment]
option 2 looks good to me! THank you

**Comment by sewkokot** [comment]
I force-pushed the second option to the last commit in the PR.

**Pull request merged**
