### PR TITLE
Effective Site Response analysis

### PR DESCRIPTION
**Pull request by harshmistry96**
Converted an example from opensees to openseespy

### CODE REVIEW

**Comment by zhuminjie** [comment]
Thanks! Can you also write a rst file so others can see the example?

**Comment by harshmistry96** [comment]
Is there any example format to write the rst file? And under which section should I upload the rst file?

**Comment by zhuminjie** [comment]
You can add it in 

https://github.com/zhuminjie/OpenSeesPyDoc/blob/master/src/geotech.rst

an example rst file is

https://github.com/zhuminjie/OpenSeesPyDoc/blob/master/src/pile.rst

**Comment by harshmistry96** [comment]
added the rst file and created the pull request.

Please let me know if any other file is required

**Pull request merged**
